### ISSUE TITLE
[Bug]: Restricted Content not playing even with no restrictions set in the account

### ISSUE THREAD

**Issue by Qualimiox** [ciderapp/Cider#1049]
### Describe the Bug

Cider won't play explicit songs for me.  The dev console shows this error:
`musickit.js:15 Uncaught (in promise) CONTENT_RESTRICTED: Content restricted
    at SerialPlaybackController.<anonymous> (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:247286)
    at Generator.next (<anonymous>)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:880
    at new Promise (<anonymous>)
    at __awaiter$1 (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:579)
    at SerialPlaybackController.play (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:246840)
    at MusicKitInstance.<anonymous> (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:335751)
    at Generator.next (<anonymous>)
    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:647)`
    
I've logged into my account and checked the account settings, there are no restrictions set. As a test, I tried enabling restrictions but allowing all content, that didn't change anything, neither did switching back to no restrictions. I can play the songs perfectly fine in either Apple Music on Android or in iTunes on the same PC. I've also tried reinstalling based on the [troubleshoot guide](https://github.com/ciderapp/Cider/wiki/Troubleshooting), did not delete any folders since none of the ones mentioned there were present on my PC. Reinstalling did not fix the issue either

Here are my content restrictions (in German, since that's my account language):
![cider_restrictions](https://user-images.githubusercontent.com/9073520/168897490-525a5ffe-fdf7-449c-84f8-ddafd2c2effe.PNG)
.

### Steps to Reproduce

1. Tried to play any explicit song
2. It doesn't play, throws the error above in console and skips to the next song

### Environment Information

- OS: Windows 10
- App Version and/or Commit ID: 1.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Qualimiox** [comment]
Update: The explicit songs are no working, I have no idea what fixed it, I only restarted Cider (which I had obviously done before as well).

**Comment by yazninja** [comment]
most likely took a while for musickit to update the restriction
