### ISSUE TITLE
[Bug]: Cider doesn't remove featuring artists from song titles when scrobbling to last.fm

### ISSUE THREAD

**Issue by WitherGuys** [ciderapp/Cider#1061]
### Describe the Bug

When scrobbling to last.fm, cider doesn't remove featuring artists from song titles even though I have enabled the setting. This also affects the _now playing_ status on last.fm.
As far as I'm aware, the feature never worked for the two months I've been using cider.

### Steps to Reproduce

1. Connect a last.fm account
2. Enable scrobbling and check the "Remove featuring artists from song title" option
3. Play any song whose name goes like "_songname_ (feat. _featuringartist_)" until it is scrobbled
4. The resulting scrobble on last.fm will still have the (feat.) part

### Environment Information

- OS: **Arch Linux** (latest)
- App Version: cider-git 1.4.7.3670.bc854ce0-1 _(installed from the AUR)_

### Anything else?

Logs of an application start and a song scrobble:
```
[2022-05-21 18:33:06.490] [info]  [AppEvents] App started
[2022-05-21 18:33:06.492] [info]  WebGPU is enabled.
[2022-05-21 18:33:11.582] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-05-21 18:33:11.671] [info]  [AppEvents] App ready
[2022-05-21 18:33:11.672] [info]  [Cider] Application is Ready. Creating Window.
[2022-05-21 18:33:11.684] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-05-21 18:33:11.712] [info]  WebSocketServer started on port: 26369
[2022-05-21 18:33:11.730] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-05-21 18:33:11.731] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    videoDecodeAcceleratorFlags: 0,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 8580,
      driverVendor: 'Nvidia',
      driverVersion: '515.43.04',
      vendorId: 4318
    }
  ]
}
[2022-05-21 18:33:11.733] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-05-21 18:33:11.733] [info]  Cider client port: 9000
[2022-05-21 18:33:11.736] [info]  Cider remote port: 6942
[2022-05-21 18:33:11.738] [info]  remote broadcasted
[2022-05-21 18:33:14.322] [info]  [LastFM][authenticateFromFile] Logging in with Session Info.
[2022-05-21 18:33:14.322] [info]  [LastFM][authenticateFromFile] Logged in. [Redacted]
[2022-05-21 18:33:14.589] [info]  [DiscordRPC][connect] Successfully Connected to Discord. Authed for user: [Redacted].
[2022-05-21 18:33:21.506] [info]  [LastFM] Successfully updated nowPlayingSong {
  artist: { corrected: '0', '#text': 'Jean Tonique' },
  track: { corrected: '0', '#text': 'Fame for Sale (feat. Jessie Chaton)' },
  ignoredMessage: { code: '0', '#text': '' },
  albumArtist: { corrected: '0', '#text': 'Jean Tonique' },
  album: { corrected: '0', '#text': 'You' }
}
[2022-05-21 18:33:27.973] [error] NOT_FOUND: 404
    at Function.responseError (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:4139)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:253212
    at Generator.next (<anonymous>)
    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:29:977)
[2022-05-21 18:33:27.979] [error] NOT_FOUND: 404
    at Function.responseError (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:4139)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:253212
    at Generator.next (<anonymous>)
    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:29:977)
[2022-05-21 18:33:27.982] [error] NOT_FOUND: 404
    at Function.responseError (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:4139)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:253212
    at Generator.next (<anonymous>)
    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:29:977)
[2022-05-21 18:33:27.986] [error] NOT_FOUND: 404
    at Function.responseError (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:4139)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:253212
    at Generator.next (<anonymous>)
    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:29:977)
[2022-05-21 18:33:27.988] [error] NOT_FOUND: 404
    at Function.responseError (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:4139)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:253212
    at Generator.next (<anonymous>)
    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:29:977)
[2022-05-21 18:33:27.989] [error] NOT_FOUND: 404
    at Function.responseError (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:4139)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:253212
    at Generator.next (<anonymous>)
    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:29:977)
[2022-05-21 18:33:28.266] [error] [LastFM] An error occurred while updating nowPlayingSong {
  message: 'Invalid parameters - Your request is missing a required parameter',
  error: 6
}
[2022-05-21 18:33:28.299] [info]  [LastFM] Successfully scrobbled:  {
  scrobble: {
    artist: { corrected: '0', '#text': '' },
    album: { corrected: '0', '#text': '' },
    track: { corrected: '0', '#text': 'no-title-found' },
    ignoredMessage: { code: '1', '#text': '' },
    albumArtist: { corrected: '0', '#text': '' },
    timestamp: '1653150807.979'
  },
  '@attr': { ignored: 1, accepted: 0 }
}
[2022-05-21 18:33:28.319] [error] [LastFM] An error occurred while updating nowPlayingSong {
  message: 'Invalid parameters - Your request is missing a required parameter',
  error: 6
}
[2022-05-21 18:33:28.377] [info]  [LastFM] Successfully scrobbled:  {
  scrobble: {
    artist: { corrected: '0', '#text': '' },
    album: { corrected: '0', '#text': '' },
    track: { corrected: '0', '#text': 'no-title-found' },
    ignoredMessage: { code: '1', '#text': '' },
    albumArtist: { corrected: '0', '#text': '' },
    timestamp: '1653150807.987'
  },
  '@attr': { ignored: 1, accepted: 0 }
}
[2022-05-21 18:33:28.409] [info]  [LastFM] Successfully scrobbled:  {
  scrobble: {
    artist: { corrected: '0', '#text': '' },
    album: { corrected: '0', '#text': '' },
    track: { corrected: '0', '#text': 'no-title-found' },
    ignoredMessage: { code: '1', '#text': '' },
    albumArtist: { corrected: '0', '#text': '' },
    timestamp: '1653150807.988'
  },
  '@attr': { ignored: 1, accepted: 0 }
}
[2022-05-21 18:33:28.427] [error] [LastFM] An error occurred while updating nowPlayingSong {
  message: 'Invalid parameters - Your request is missing a required parameter',
  error: 6
}
[2022-05-21 18:33:28.584] [error] NOT_FOUND: 404
    at Function.responseError (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:4139)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:253212
    at Generator.next (<anonymous>)
    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:29:977)
[2022-05-21 18:33:28.589] [error] NOT_FOUND: 404
    at Function.responseError (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:4139)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:253212
    at Generator.next (<anonymous>)
    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:29:977)
[2022-05-21 18:33:28.836] [error] [LastFM] An error occurred while updating nowPlayingSong {
  message: 'Invalid parameters - Your request is missing a required parameter',
  error: 6
}
[2022-05-21 18:33:28.858] [info]  [LastFM] Successfully scrobbled:  {
  scrobble: {
    artist: { corrected: '0', '#text': '' },
    album: { corrected: '0', '#text': '' },
    track: { corrected: '0', '#text': 'no-title-found' },
    ignoredMessage: { code: '1', '#text': '' },
    albumArtist: { corrected: '0', '#text': '' },
    timestamp: '1653150808.589'
  },
  '@attr': { ignored: 1, accepted: 0 }
}
[2022-05-21 18:33:29.604] [info]  [LastFM] Successfully updated nowPlayingSong {
  artist: { corrected: '0', '#text': 'French 79' },
  track: { corrected: '0', '#text': 'Diamond Veins (feat. Sarah Rebecca)' },
  ignoredMessage: { code: '0', '#text': '' },
  albumArtist: { corrected: '0', '#text': 'French 79' },
  album: { corrected: '0', '#text': 'Olympic' }
}
[2022-05-21 18:34:41.717] [info]  [LastFM] Successfully scrobbled:  {
  scrobble: {
    artist: { corrected: '0', '#text': 'French 79' },
    album: { corrected: '0', '#text': 'Olympic' },
    track: { corrected: '0', '#text': 'Diamond Veins (feat. Sarah Rebecca)' },
    ignoredMessage: { code: '0', '#text': '' },
    albumArtist: { corrected: '0', '#text': 'French 79' },
    timestamp: '1653150881.325'
  },
  '@attr': { ignored: 0, accepted: 1 }
}

```

Resulting scrobble shown in logs above;
![Screenshot_20220521_184424](https://user-images.githubusercontent.com/61845593/169661255-1e45ecb3-ae5d-431b-9bd6-69b9984217fc.png)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Lastfm was reworked, should be good now.
