### ISSUE TITLE
[Bug]: Unable to connect last.fm 

### ISSUE THREAD

**Issue by jonam-samarah** [ciderapp/Cider#1129]
### Describe the Bug

While trying to connect last.fm, its connection authentication page is opened and on clicking "Yes, allow access" button on last.fm page, a redirect request is asked to open Cider application. But when doing so the last.fm connect button stays in "connecting.." state and reverts back to "Connect" state after few seconds thus failed to connect

### Steps to Reproduce

1. Open settings
2. Switch to Connectivity Tab
3. Click Last.fm scrobbling "Connect" button
4. Click "Yes, allow access" in the last.fm authentication page

### Environment Information

- OS: Fedora Linux 36 (Workstation Edition) x86_64
- App Version and/or Commit ID: Version 1.5.386 (Installed through Flatpak)

### Anything else?

[2022-06-05 11:43:14.528] [info]  [AppEvents] App started
[2022-06-05 11:43:14.636] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-05 11:43:14.680] [info]  [AppEvents] App ready
[2022-06-05 11:43:14.680] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-05 11:43:14.694] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=37501
[2022-06-05 11:43:14.713] [info]  WebSocketServer started on port: 26369
[2022-06-05 11:43:14.718] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-05 11:43:14.719] [info]  [InstanceHandler] (second-instance) Instance started with /app/cider/cider,--enable-crashpad,--allow-file-access-from-files,--secure-schemes,--bypasscsp-schemes=sentry-ipc,--cors-schemes=sentry-ipc,--fetch-schemes=sentry-ipc,--service-worker-schemes,--standard-schemes,--streaming-schemes,--js-flags=--max-old-space-size=350,--js-flags=--expose_gc,--enable-accelerated-mjpeg-decode,--enable-accelerated-video,--disable-gpu-driver-bug-workarounds,--ignore-gpu-blacklist,--enable-native-gpu-memory-buffers,--enable-accelerated-video-decode,--enable-gpu-rasterization,--enable-native-gpu-memory-buffers,--enable-oop-rasterization,--disable-features=MediaSessionService
[2022-06-05 11:43:14.719] [info]  /app/cider/cider
[2022-06-05 11:43:14.730] [info]  --enable-crashpad
[2022-06-05 11:43:14.740] [info]  --allow-file-access-from-files
[2022-06-05 11:43:14.750] [info]  --secure-schemes
[2022-06-05 11:43:14.761] [info]  --bypasscsp-schemes=sentry-ipc
[2022-06-05 11:43:14.772] [info]  --cors-schemes=sentry-ipc
[2022-06-05 11:43:14.782] [info]  --fetch-schemes=sentry-ipc
[2022-06-05 11:43:14.792] [info]  --service-worker-schemes
[2022-06-05 11:43:14.802] [info]  --standard-schemes
[2022-06-05 11:43:14.812] [info]  --streaming-schemes
[2022-06-05 11:43:14.824] [info]  --js-flags=--max-old-space-size=350
[2022-06-05 11:43:14.834] [info]  --js-flags=--expose_gc
[2022-06-05 11:43:14.843] [info]  --enable-accelerated-mjpeg-decode
[2022-06-05 11:43:14.853] [info]  --enable-accelerated-video
[2022-06-05 11:43:14.863] [info]  --disable-gpu-driver-bug-workarounds
[2022-06-05 11:43:14.875] [info]  --ignore-gpu-blacklist
[2022-06-05 11:43:14.885] [info]  --enable-native-gpu-memory-buffers
[2022-06-05 11:43:14.895] [info]  --enable-accelerated-video-decode
[2022-06-05 11:43:14.905] [info]  --enable-gpu-rasterization
[2022-06-05 11:43:14.918] [info]  --enable-native-gpu-memory-buffers
[2022-06-05 11:43:14.928] [info]  --enable-oop-rasterization
[2022-06-05 11:43:14.938] [info]  --disable-features=MediaSessionService
[2022-06-05 11:43:14.949] [info]  [Cider] Another instance has been found, quitting.
[2022-06-05 11:43:14.949] [info]  Example plugin stopped
[2022-06-05 11:43:14.949] [warn]  Cider exited.
[2022-06-05 11:43:14.973] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 29663,
      vendorId: 4098
    }
  ]
}
[2022-06-05 11:43:14.974] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-05 11:43:14.974] [info]  Cider client port: 37501
[2022-06-05 11:43:14.984] [info]  Cider remote port: 42945
[2022-06-05 11:43:14.985] [info]  remote broadcasted
[2022-06-05 11:43:14.992] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-05 11:43:14.993] [error] TypeError: Cannot read properties of null (reading 'on')
    at AppEvents.InitTray (/app/cider/resources/app.asar/src/main/base/app.ts:279:26)
    at AppEvents.bwCreated (/app/cider/resources/app.asar/src/main/base/app.ts:148:18)
    at /app/cider/resources/app.asar/src/main/index.ts:53:15
    at Generator.next (<anonymous>)
    at fulfilled (/app/cider/resources/app.asar/build/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-05 11:43:14.993] [error] (node:12) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'on')
    at AppEvents.InitTray (/app/cider/resources/app.asar/src/main/base/app.ts:279:26)
    at AppEvents.bwCreated (/app/cider/resources/app.asar/src/main/base/app.ts:148:18)
    at /app/cider/resources/app.asar/src/main/index.ts:53:15
    at Generator.next (<anonymous>)
    at fulfilled (/app/cider/resources/app.asar/build/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-05 11:43:14.993] [error] (node:12) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Lastfm was reworked, should be good now.
