### ISSUE TITLE
[Bug]: Cider stops responding when clicking on "Songs"

### ISSUE THREAD

**Issue by LukasPietzschmann** [ciderapp/Cider#1161]
### Describe the Bug

This might be a duplicate of https://github.com/ciderapp/Cider/issues/1146, but I'm not sure, as Cider is not really crashing on my system.

Cider launches in the "home" tab by default. There I can start and stop playing music without any problems. But as soon as I click on the "Songs" tab, the message "Updating library songs...(0/0)" shows up and the app freezes. I have to force quit and restart it to use it again.

### Steps to Reproduce

1. Open Cider
2. Click on "Songs"

### Environment Information

- OS: Fedora 36
- App Version: Version 1.5.1 installed via Flatpak

### Anything else?

Logs:
`[2022-06-12 10:16:53.642] [info]  [AppEvents] App started
[2022-06-12 10:16:53.765] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-12 10:16:53.829] [info]  [AppEvents] App ready
[2022-06-12 10:16:53.830] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-12 10:16:54.092] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:16:54.092] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:16:54.093] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-12 10:16:54.093] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-12 10:16:54.116] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:16:54.116] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:16:54.117] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:16:54.117] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2022-06-12 10:16:54.791] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-12 10:16:54.813] [info]  WebSocketServer started on port: 26369
[2022-06-12 10:16:54.820] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'updated',
    version: '4.10.2391.0'
  }
}
[2022-06-12 10:16:54.843] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 5688,
      vendorId: 4098
    }
  ]
}
[2022-06-12 10:16:54.844] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-12 10:16:54.844] [info]  Cider client port: 9000
[2022-06-12 10:16:54.846] [info]  Cider remote port: 6942
[2022-06-12 10:16:54.848] [info]  remote broadcasted
[2022-06-12 10:19:49.924] [info]  Example plugin stopped
[2022-06-12 10:19:49.925] [warn]  Cider exited.
[2022-06-12 10:19:51.541] [info]  [AppEvents] App started
[2022-06-12 10:19:51.674] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-12 10:19:51.741] [info]  [AppEvents] App ready
[2022-06-12 10:19:51.742] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-12 10:19:51.756] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-12 10:19:51.780] [info]  WebSocketServer started on port: 26369
[2022-06-12 10:19:51.788] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-12 10:19:51.812] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 5688,
      vendorId: 4098
    }
  ]
}
[2022-06-12 10:19:51.813] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-12 10:19:51.814] [info]  Cider client port: 9000
[2022-06-12 10:19:51.815] [info]  Cider remote port: 6942
[2022-06-12 10:19:51.817] [info]  remote broadcasted
[2022-06-12 10:19:51.846] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:19:51.846] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:19:51.847] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-12 10:19:51.847] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-12 10:19:51.864] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:19:51.865] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:19:51.865] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:19:51.865] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2022-06-12 10:20:32.267] [info]  Example plugin stopped
[2022-06-12 10:20:32.269] [warn]  Cider exited.
[2022-06-12 10:20:44.456] [info]  [AppEvents] App started
[2022-06-12 10:20:44.621] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-12 10:20:44.710] [info]  [AppEvents] App ready
[2022-06-12 10:20:44.711] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-12 10:20:44.728] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-12 10:20:44.763] [info]  WebSocketServer started on port: 26369
[2022-06-12 10:20:44.772] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-12 10:20:44.803] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 5688,
      vendorId: 4098
    }
  ]
}
[2022-06-12 10:20:44.804] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-12 10:20:44.804] [info]  Cider client port: 9000
[2022-06-12 10:20:44.806] [info]  Cider remote port: 6942
[2022-06-12 10:20:44.808] [info]  remote broadcasted
[2022-06-12 10:20:44.836] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:20:44.836] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:20:44.837] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-12 10:20:44.837] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-12 10:20:44.838] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:20:44.839] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:20:44.839] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:20:44.839] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2022-06-12 10:21:56.072] [info]  Example plugin stopped
[2022-06-12 10:21:56.074] [warn]  Cider exited.
[2022-06-12 10:24:17.444] [info]  [AppEvents] App started
[2022-06-12 10:24:17.575] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-12 10:24:17.642] [info]  [AppEvents] App ready
[2022-06-12 10:24:17.642] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-12 10:24:17.656] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-12 10:24:17.681] [info]  WebSocketServer started on port: 26369
[2022-06-12 10:24:17.688] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-12 10:24:17.714] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 5688,
      vendorId: 4098
    }
  ]
}
[2022-06-12 10:24:17.715] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-12 10:24:17.715] [info]  Cider client port: 9000
[2022-06-12 10:24:17.717] [info]  Cider remote port: 6942
[2022-06-12 10:24:17.719] [info]  remote broadcasted
[2022-06-12 10:24:17.939] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:24:17.940] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:24:17.940] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-12 10:24:17.941] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-12 10:24:18.091] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:24:18.091] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:24:18.091] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:24:18.091] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2022-06-12 10:26:45.941] [info]  Example plugin stopped
[2022-06-12 10:26:45.943] [warn]  Cider exited.
[2022-06-12 10:26:51.483] [info]  [AppEvents] App started
[2022-06-12 10:26:51.610] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-12 10:26:51.680] [info]  [AppEvents] App ready
[2022-06-12 10:26:51.681] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-12 10:26:51.697] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-12 10:26:51.723] [info]  WebSocketServer started on port: 26369
[2022-06-12 10:26:51.730] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-12 10:26:51.756] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 5688,
      vendorId: 4098
    }
  ]
}
[2022-06-12 10:26:51.757] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-12 10:26:51.758] [info]  Cider client port: 9000
[2022-06-12 10:26:51.759] [info]  Cider remote port: 6942
[2022-06-12 10:26:51.761] [info]  remote broadcasted
[2022-06-12 10:26:51.788] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:26:51.789] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:26:51.789] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-12 10:26:51.789] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-12 10:26:51.855] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:26:51.855] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:26:51.856] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:26:51.856] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2022-06-12 10:28:31.856] [info]  Example plugin stopped
[2022-06-12 10:28:31.857] [warn]  Cider exited.
[2022-06-12 10:28:36.098] [info]  [AppEvents] App started
[2022-06-12 10:28:36.231] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-12 10:28:36.302] [info]  [AppEvents] App ready
[2022-06-12 10:28:36.303] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-12 10:28:36.320] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-12 10:28:36.349] [info]  WebSocketServer started on port: 26369
[2022-06-12 10:28:36.357] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-12 10:28:36.384] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 5688,
      vendorId: 4098
    }
  ]
}
[2022-06-12 10:28:36.385] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-12 10:28:36.386] [info]  Cider client port: 9000
[2022-06-12 10:28:36.387] [info]  Cider remote port: 6942
[2022-06-12 10:28:36.389] [info]  remote broadcasted
[2022-06-12 10:28:36.420] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:28:36.421] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:28:36.421] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-12 10:28:36.422] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-12 10:28:36.422] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:28:36.423] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:28:36.423] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:28:36.423] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2022-06-12 10:31:34.628] [info]  Example plugin stopped
[2022-06-12 10:31:34.631] [warn]  Cider exited.
[2022-06-12 10:31:36.598] [info]  [AppEvents] App started
[2022-06-12 10:31:36.729] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-12 10:31:36.795] [info]  [AppEvents] App ready
[2022-06-12 10:31:36.796] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-12 10:31:36.810] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-12 10:31:36.836] [info]  WebSocketServer started on port: 26369
[2022-06-12 10:31:36.843] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-12 10:31:36.870] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 5688,
      vendorId: 4098
    }
  ]
}
[2022-06-12 10:31:36.871] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-12 10:31:36.871] [info]  Cider client port: 9000
[2022-06-12 10:31:36.873] [info]  Cider remote port: 6942
[2022-06-12 10:31:36.874] [info]  remote broadcasted
[2022-06-12 10:31:37.107] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:31:37.107] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:31:37.108] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-12 10:31:37.108] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-12 10:31:37.157] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-12 10:31:37.158] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:31:37.158] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-12 10:31:37.158] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Juice805** [comment]
Also having this problem on the Windows version via the store

**Comment by kgarner7** [comment]
I have a similar problem, and it looks like it is because Cider is attempting to render your entire library at once (as opposed to lazily loading as you scroll, pagination, etc). Manually loading only the first 1000 songs completed in a much more reasonable time.

**Comment by SkyRexHUN** [comment]
I have over 5k songs, the app practically becomes unusable for minutes before rendering all my library, and even after it becomes slow and the animations are delayed like crazy.

**Comment by LukasPietzschmann** [comment]
So I just updated the flatpak package and I looks like this bug is no longer present. @SkyRexHUN , @kgarner7, @Juice805 did you also try the new version and is this bug also gone on your machine?

**Comment by kgarner7** [comment]
Yes! 1.5.1 has a few bugfixes + additions that are designed to deal with large libraries (in the songs tab, albums tab, and playlists)

**Comment by LukasPietzschmann** [comment]
Alright, then I'll go ahead and close this issue.
