### ISSUE TITLE
[Bug]: Cider does not export its media playback to the kde system tray media widget. 

### ISSUE THREAD

**Issue by linusrg1** [ciderapp/Cider#1190]
### Describe the Bug

When I tried to view my music in the kde media widget in the system tray it did not appear there. This incidentally also prevents headset play and pause forward/back functionality from working as well due to the kde media widget being unable to access the media being played back. 

### Steps to Reproduce

Open app
Play music
Check playback status in the kde media widget
It does not appear there. 

### Environment Information

- OS: Fedora 36 with kde 5.25.0
- App Version and/or Commit ID: Version 1.51

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by linusrg1** [comment]
`[2022-06-22 07:12:57.873] [info]  [AppEvents] App started
[2022-06-22 07:12:58.349] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-22 07:12:58.533] [info]  [AppEvents] App ready
[2022-06-22 07:12:58.535] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-22 07:12:59.166] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 07:12:59.167] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 07:12:59.169] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-22 07:12:59.170] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-22 07:12:59.185] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 07:12:59.186] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 07:12:59.187] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 07:12:59.188] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2022-06-22 07:13:00.179] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-22 07:13:00.233] [info]  WebSocketServer started on port: 26369
[2022-06-22 07:13:00.253] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'updated',
    version: '4.10.2391.0'
  }
}
[2022-06-22 07:13:00.315] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 278,
      vendorId: 32902
    }
  ]
}
[2022-06-22 07:13:00.316] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-22 07:13:00.317] [info]  Cider client port: 9000
[2022-06-22 07:13:00.321] [info]  Cider remote port: 6942
[2022-06-22 07:13:00.325] [info]  remote broadcasted
[2022-06-22 07:14:06.506] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 07:14:06.507] [error] DBusError: org.freedesktop.DBus.Error.ServiceUnknown
    at _methodReturnHandlers.<computed> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (node:events:526:28)
    at EventEmitter.emit (node:domain:475:12)
    at /app/cider/resources/app.asar/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at emitReadable_ (node:internal/streams/readable:578:12)
[2022-06-22 07:14:06.509] [error] (node:13) UnhandledPromiseRejectionWarning: DBusError: org.freedesktop.DBus.Error.ServiceUnknown
    at _methodReturnHandlers.<computed> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (node:events:526:28)
    at EventEmitter.emit (node:domain:475:12)
    at /app/cider/resources/app.asar/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at emitReadable_ (node:internal/streams/readable:578:12)
[2022-06-22 07:14:06.509] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
[2022-06-22 10:45:32.275] [info]  [AppEvents] App started
[2022-06-22 10:45:32.759] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-22 10:45:33.079] [info]  [AppEvents] App ready
[2022-06-22 10:45:33.091] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-22 10:45:33.202] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-22 10:45:33.338] [info]  WebSocketServer started on port: 26369
[2022-06-22 10:45:33.360] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-22 10:45:33.464] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 278,
      vendorId: 32902
    }
  ]
}
[2022-06-22 10:45:33.467] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-22 10:45:33.468] [info]  Cider client port: 9000
[2022-06-22 10:45:33.474] [info]  Cider remote port: 6942
[2022-06-22 10:45:33.479] [info]  remote broadcasted
[2022-06-22 10:45:34.210] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 10:45:34.212] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 10:45:34.214] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-22 10:45:34.215] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-22 10:45:34.220] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 10:45:34.221] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 10:45:34.222] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 10:45:34.223] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2022-06-22 10:48:48.185] [info]  Example plugin stopped
[2022-06-22 10:48:48.196] [warn]  Cider exited.
[2022-06-22 11:52:39.757] [info]  [AppEvents] App started
[2022-06-22 11:52:40.227] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-22 11:52:40.497] [info]  [AppEvents] App ready
[2022-06-22 11:52:40.503] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-22 11:52:40.549] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-22 11:52:40.819] [info]  WebSocketServer started on port: 26369
[2022-06-22 11:52:40.833] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-22 11:52:40.912] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 278,
      vendorId: 32902
    }
  ]
}
[2022-06-22 11:52:40.915] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-22 11:52:40.916] [info]  Cider client port: 9000
[2022-06-22 11:52:40.921] [info]  Cider remote port: 6942
[2022-06-22 11:52:40.926] [info]  remote broadcasted
[2022-06-22 11:52:41.419] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 11:52:41.420] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 11:52:41.421] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-22 11:52:41.421] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-22 11:52:41.423] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 11:52:41.423] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 11:52:41.424] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 11:52:41.424] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2022-06-22 11:59:05.570] [info]  /home/linus/.var/app/sh.cider.Cider/config/Cider/Themes/gh_496435838
[2022-06-22 12:13:58.523] [info]  Example plugin stopped
[2022-06-22 12:13:58.533] [warn]  Cider exited.
[2022-06-22 12:14:03.283] [info]  [AppEvents] App started
[2022-06-22 12:14:03.608] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-22 12:14:03.728] [info]  [AppEvents] App ready
[2022-06-22 12:14:03.730] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-22 12:14:03.776] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-22 12:14:03.827] [info]  WebSocketServer started on port: 26369
[2022-06-22 12:14:03.842] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-22 12:14:03.907] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 278,
      vendorId: 32902
    }
  ]
}
[2022-06-22 12:14:03.908] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-22 12:14:03.910] [info]  Cider client port: 9000
[2022-06-22 12:14:03.914] [info]  Cider remote port: 6942
[2022-06-22 12:14:03.917] [info]  remote broadcasted
[2022-06-22 12:14:04.252] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 12:14:04.253] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 12:14:04.254] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-22 12:14:04.255] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-22 12:14:04.314] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 12:14:04.315] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 12:14:04.315] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 12:14:04.316] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2022-06-22 12:17:17.177] [info]  Example plugin stopped
[2022-06-22 12:17:17.192] [warn]  Cider exited.
[2022-06-22 12:17:51.239] [info]  [AppEvents] App started
[2022-06-22 12:17:51.658] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-06-22 12:17:51.788] [info]  [AppEvents] App ready
[2022-06-22 12:17:51.790] [info]  [Cider] Application is Ready. Creating Window.
[2022-06-22 12:17:51.945] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[2022-06-22 12:17:52.008] [info]  WebSocketServer started on port: 26369
[2022-06-22 12:17:52.034] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2022-06-22 12:17:52.122] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 278,
      vendorId: 32902
    }
  ]
}
[2022-06-22 12:17:52.125] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-06-22 12:17:52.125] [info]  Cider client port: 9000
[2022-06-22 12:17:52.130] [info]  Cider remote port: 6942
[2022-06-22 12:17:52.135] [info]  remote broadcasted
[2022-06-22 12:17:52.316] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 12:17:52.317] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 12:17:52.319] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-06-22 12:17:52.319] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-06-22 12:17:52.324] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-06-22 12:17:52.324] [error] SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 12:17:52.325] [error] (node:13) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /app/cider/resources/app.asar/node_modules/electron-fetch/lib/index.js:297:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22 12:17:52.326] [error] (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
`

Here ya go.

**Comment by linusrg1** [comment]
It suddenly started working. Tbf kde 5.25.0 is kinda buggy. Maybe I shoulda thought about that before posting here. I apologize.

**Comment by linusrg1** [comment]
There is another linux desktop I experimented with to see if this issue persisted on there as well and it did. That environment was cinnamon, and just like kde it has mpris support baked in by default so I think there is definitely a bug in the linux version of cider somewhere.
