### ISSUE TITLE
[Bug]: Can not start app on macOS

### ISSUE THREAD

**Issue by romanzipp** [ciderapp/Cider#1248]
### Describe the Bug

I can not start Cider on macOS. I've tried running it from the .dmg archive or .pkg installer.

If starting in **native** mode, the following exception will be displayed: (looks like node/electron dialog, App does not quit until "OK" in pressed)

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: dlopen(/Applications/Cider.app/Contents/Resources/app.asar.unpacked/node_modules/cider_utils/index.node, 0x0001): tried: '/Applications/Cider.app/Contents/Resources/app.asar.unpacked/node_modules/cider_utils/index.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (/Applications/Cider.app/Contents/Resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
at Object.<anonymous> (/Applications/Cider.app/Contents/Resources/app.asar/node_modules/cider_utils/index.js:1:85)
at Module._compile (/Applications/Cider.app/Contents/Resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

When opening Cider via **Rosetta** translation another exception occurs: (via macOS error reporter). Hit me up if you need the full stacktrace.

```
Process:               Cider [77625]
Path:                  /Applications/Cider.app/Contents/MacOS/Cider
Identifier:            cider
Version:               1.5.1 (1.5.1)
Code Type:             X86-64 (Translated)

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x000000742074636c
Exception Codes:       0x0000000000000002, 0x000000742074636c
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 10 Bus error: 10
Terminating Process:   exc handler [77625]
```

#### Native

1. Install via .dmg archive or .pkg installer
2. Start app
3. Exception dialog appears

#### Rosetta

1. Install via .dmg archive or .pkg installer
2. Toggle "Open using Rosetta" in app info properties
3. Start app
4. macOS Exception dialog appears

### Environment Information

- OS: macOS 12.4 (21F79)
- App Version and/or Commit ID: latest (6. July 2022 at 05:54 UTC)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
This is a known error on the latest main branch.
Please switch to stable for the time being.

**Comment by romanzipp** [comment]
I compiled it myself on 46eb12097363b215c4bb19aa4ed190e9918db9d5 and it works fine 👍

**Comment by maikirakiwi** [comment]
Should be resolved on the latest build
