### ISSUE TITLE
[Bug]: i need to restart the app after playing one track

### ISSUE THREAD

**Issue by Minecon724** [ciderapp/Cider#1282]
### Describe the Bug

A bug happened!

### Steps to Reproduce

1. Play any song, works fine
2. Play any song, this time it won't load

### Environment Information

- OS: debian 11
- App Version and/or Commit ID: 1.5.1 415 .deb

### Anything else?

there are literally no errors in the console,
except for this one that popped up once, unsure if related:
```
[19:18:03.312] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[19:18:03.314] [error] TypeError: Cannot read properties of null (reading 'gain')
    at http://localhost:9000/main/vueapp.js:1024:86
    at wrappedCallback (https://api.cider.sh/musickit.js:44:288320)
    at https://api.cider.sh/musickit.js:29:20834
    at Array.forEach (<anonymous>)
    at PubSub.publish (https://api.cider.sh/musickit.js:29:20822)
    at AudioPlayer.set nowPlayingItem [as nowPlayingItem] (https://api.cider.sh/musickit.js:44:53103)
    at AudioPlayer.<anonymous> (https://api.cider.sh/musickit.js:44:56704)
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:29:977)
[19:18:03.317] [error] (node:10650) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'gain')
    at http://localhost:9000/main/vueapp.js:1024:86
    at wrappedCallback (https://api.cider.sh/musickit.js:44:288320)
    at https://api.cider.sh/musickit.js:29:20834
    at Array.forEach (<anonymous>)
    at PubSub.publish (https://api.cider.sh/musickit.js:29:20822)
    at AudioPlayer.set nowPlayingItem [as nowPlayingItem] (https://api.cider.sh/musickit.js:44:53103)
    at AudioPlayer.<anonymous> (https://api.cider.sh/musickit.js:44:56704)
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:29:977)
(Use `cider --trace-warnings ...` to show where the warning was created)
[19:18:03.318] [error] (node:10650) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Minecon724** [comment]
could a ~7mbps connection be a problem here

**Comment by Minecon724** [comment]
still an issue (on [this](https://github.com/ciderapp/cider-releases/releases/tag/v1.5.1-beta.435) release)
