### ISSUE TITLE
[Bug]: Skipping songs (play for a split second, then skip)

### ISSUE THREAD

**Issue by marclallen** [ciderapp/Cider#1376]
### Describe the Bug

I have a playlist with a lot of my own imported music along with a lot of Apple Music.  I often see my own stuff get sorta skipped.

Log file attached.  

Error log reports:

[2022-08-19 12:24:06.948] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-08-19 12:24:06.949] [error] TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Program Files\WindowsApps\27554FireDevElijahKlauman.CiderAlpha_1.5.3.0_x64__270bejk4xgzqp\app\resources\app.asar\node_modules\electron-fetch\lib\index.js:1236:11)
    at C:\Program Files\WindowsApps\27554FireDevElijahKlauman.CiderAlpha_1.5.3.0_x64__270bejk4xgzqp\app\resources\app.asar\node_modules\electron-fetch\lib\index.js:1304:21
    at new Promise (<anonymous>)
    at C:\Program Files\WindowsApps\27554FireDevElijahKlauman.CiderAlpha_1.5.3.0_x64__270bejk4xgzqp\app\resources\app.asar\node_modules\electron-fetch\lib\index.js:1301:29
[2022-08-19 12:24:06.950] [error] (node:29048) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Program Files\WindowsApps\27554FireDevElijahKlauman.CiderAlpha_1.5.3.0_x64__270bejk4xgzqp\app\resources\app.asar\node_modules\electron-fetch\lib\index.js:1236:11)
    at C:\Program Files\WindowsApps\27554FireDevElijahKlauman.CiderAlpha_1.5.3.0_x64__270bejk4xgzqp\app\resources\app.asar\node_modules\electron-fetch\lib\index.js:1304:21
    at new Promise (<anonymous>)
    at C:\Program Files\WindowsApps\27554FireDevElijahKlauman.CiderAlpha_1.5.3.0_x64__270bejk4xgzqp\app\resources\app.asar\node_modules\electron-fetch\lib\index.js:1301:29
[2022-08-19 12:24:06.950] [error] (node:29048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 267)

AND:

[2022-08-19 12:24
[Cider.log](https://github.com/ciderapp/Cider/files/9383848/Cider.log)
:07.401] [info]  TypeError: Cannot read properties of undefined (reading 'setArtwork')
    at C:\Program Files\WindowsApps\27554FireDevElijahKlauman.CiderAlpha_1.5.3.0_x64__270bejk4xgzqp\app\resources\app.asar\src\main\plugins\raop.ts:346:39
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[Cider.log](https://github.com/ciderapp/Cider/files/9383853/Cider.log)

### Steps to Reproduce

Not sure really.. I just play my playlist and it happens.  Often.

### Environment Information

- OS: Windows 10
- App Version and/or Commit ID: 1.5.3 (MS Store version)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by DysphoricUnicorn** [comment]
This is probably the same bug as #1373

**Comment by marclallen** [comment]
Good catch!  It probaby is the same, but is not exactly the same symptoms.  

1. I can play the song if I manually request 1.
2. A given song doesn't always get skipped.  If a set of songs is skipped, I can go back in the shuffle playlist and play them (sometimes).
3. The other ticket only said it wasn't an Apple Music song.  Mine aren't, but they are uploaded to the apple cloud, so they aren't being played locally.

No idea if any of that is any help or not.

**Comment by marclallen** [comment]
I'm torn.  Mostly 'Bummer!' But partially a puzzle to look into.

Thanks, @vapormusic.  If you have time/inclination, would you mind linking me to an MusicKitJS ticket for this bug or briefly describing it?
