### ISSUE TITLE
[Bug]: Ubuntu 22.04: Cider freezes after Apple login.

### ISSUE THREAD

**Issue by pplachta** [ciderapp/Cider#1419]
### Describe the Bug

After the Apple login screen, Cider just freezes.
I tried 1.5.6 and 1.5.7-beta.50. I tried both skins and the enhanced sound mode on/off, but to no avail.

### Steps to Reproduce

Run cider, go through setup steps.

### Environment Information

- OS: Ubuntu 22.04
- App Version and/or Commit ID: 1.5.6 and  1.5.7-beta.50

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by cryptofyre** [comment]
Cannot reproduce, not enough information given.

**Comment by pplachta** [comment]
It would be helpful to know what other information you need, rather than closing. Cider is still not working on my system. I tried building it from HEAD as well.

By running "cider" from the command line I got this bit of log

[17:51:30.185] [error] [lastfm.js] An error was encountered: Error: Attempted to register a second handler for 'lastfm:url'
[17:51:30.186] [error] Error: Attempted to register a second handler for 'lastfm:url'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at lastfm.onRendererReady (/opt/Cider/resources/app.asar/src/main/plugins/lastfm.ts:36:30)
    at Plugins.callPlugins (/opt/Cider/resources/app.asar/src/main/base/plugins.ts:107:42)
    at /opt/Cider/resources/app.asar/src/main/index.ts:67:13
    at node:electron/js2c/browser_init:193:579
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11327)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at EventEmitter.emitter.emit (/opt/Cider/resources/app.asar/node_modules/@sentry/electron/src/main/integrations/electron-breadcrumbs.ts:200:14)

**Comment by coredev-uk** [comment]
This should've been fixed in b57f972fafc834710f7c14bb4f7f0b2fc149faf4.
