### ISSUE TITLE
[Bug]: Playing a song from the Listen Now section of the app causes the Mpris service to exit and/or crash

### ISSUE THREAD

**Issue by ScottStaschke** [ciderapp/Cider#1425]
### Describe the Bug

After initially opening the app, cider is listed as an available player when running:
playerctl -l

However, after starting a song from the app, specifically from the Listen Now section, the Mpris service exits and/or crashes, and no longer shows up in the available players list when doing:
playerctl -l

### Steps to Reproduce

1. Open app.
2. Check available players list by running something like "playerctl -l" in a terminal window.
3. Go to the Listen Now section in the app, and select a playlist and/or song, and play it.
4. Check available players list by running something like "playerctl -l" in a terminal window.
5. Cider is no longer listed as an available player to choose from.

### Environment Information

- OS: Arch Linux
- App Version and/or Commit ID: Version 1.5.7 Beta 48

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by VladYagl** [comment]
I get the same issue. Also the same OS and App version. Can provide an error log from console:
```
[10:54:35.570] [error] [mpris.js] An error was encountered: Error: Tried to write a message to a closed stream
[10:54:35.571] [error] Error: Tried to write a message to a closed stream
    at EventEmitter.self.message (/opt/cider/resources/app.asar/node_modules/dbus-next/lib/connection.js:92:26)
    at MessageBus.send (/opt/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:371:22)
    at EventEmitter.propertiesChangedHandler (/opt/cider/resources/app.asar/node_modules/dbus-next/lib/service/object.js:30:16)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at Function.emitPropertiesChanged (/opt/cider/resources/app.asar/node_modules/dbus-next/lib/service/interface.js:386:20)
    at PlayerInterface.setProperty (/opt/cider/resources/app.asar/node_modules/mpris-service/src/interfaces/mpris-interface.js:51:19)
    at Player.set [as metadata] (/opt/cider/resources/app.asar/node_modules/mpris-service/src/index.js:292:13)
    at Function.updateMetaData (/opt/cider/resources/app.asar/src/main/plugins/mpris.ts:104:26)
    at mpris.onNowPlayingItemDidChange (/opt/cider/resources/app.asar/src/main/plugins/mpris.ts:173:11)
```

**Comment by coredev-uk** [comment]
What song are you trying to play?

**Comment by ScottStaschke** [comment]
It can be just about anything from the "Listen Now" section.

Just started Cider:
![image](https://user-images.githubusercontent.com/3875557/189728897-c80089e3-cf98-40e5-94e6-7abef277fb7e.png)

Click the play button that shows up on one of these playlists, for example:
![image](https://user-images.githubusercontent.com/3875557/189729232-6f51cef2-8f7e-489c-b951-3176cf75a235.png)

After that starts playing:
![image](https://user-images.githubusercontent.com/3875557/189729403-fce281ad-d4a6-4a39-94b7-0d19f8c3caee.png)

**Comment by coredev-uk** [comment]
I cannot replicate this issue then.

**Comment by ScottStaschke** [comment]
I just updated to the latest Cider version: 1.5.7 Beta 78, and confirmed the same findings.
Is there any other information that could be provided that might help you recreate it?

**Comment by ScottStaschke** [comment]
Just as @VladYagl posted, as soon as I click the play button on one of those playlists, this occurs in the logs:
`[15:58:30.787] [error] [mpris.js] An error was encountered: Error: Tried to write a message to a closed stream
[15:58:30.788] [error] Error: Tried to write a message to a closed stream
    at EventEmitter.self.message (/opt/cider/resources/app.asar/node_modules/dbus-next/lib/connection.js:92:26)
    at MessageBus.send (/opt/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:371:22)
    at EventEmitter.propertiesChangedHandler (/opt/cider/resources/app.asar/node_modules/dbus-next/lib/service/object.js:30:16)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at Function.emitPropertiesChanged (/opt/cider/resources/app.asar/node_modules/dbus-next/lib/service/interface.js:386:20)
    at PlayerInterface.setProperty (/opt/cider/resources/app.asar/node_modules/mpris-service/src/interfaces/mpris-interface.js:51:19)
    at Player.set [as metadata] (/opt/cider/resources/app.asar/node_modules/mpris-service/src/index.js:292:13)
    at Function.updateMetaData (/opt/cider/resources/app.asar/src/main/plugins/mpris.ts:104:26)
    at mpris.onNowPlayingItemDidChange (/opt/cider/resources/app.asar/src/main/plugins/mpris.ts:173:11)
[15:58:30.821] [error] [mpris.js] An error was encountered: Error: Tried to write a message to a closed stream`

This happens three times as soon as the song starts playing.

For what it's worth, I found this issue occurred in another player as well.  I don't know if the issue is the same or similar, but here's the thread for reference: https://github.com/nukeop/nuclear/issues/1081

**Comment by ScottStaschke** [comment]
I suppose I could do a PR for this, but it looks like this fix does the trick:
![image](https://user-images.githubusercontent.com/3875557/189761065-3a9f41ff-9148-445f-9df8-46af9ee00600.png)

I just changed the replace from "." to anything that's not a letter or a number in src/main/plugins/mpris.ts.

**Comment by coredev-uk** [comment]
I’ll commit the code in a few hours, thanks.

**Comment by coredev-uk** [comment]
You could try this on your system, the Linux build of electron allows you to play media in an uncompiled state.

**Comment by ScottStaschke** [comment]
Go ahead and take it.  I'm glad it was a relatively simple fix.  

I appreciate the time you took to look at this and other pieces of the app that you're involved with.  You, and all of the other contributors.
