### ISSUE TITLE
[Bug]: Can't Play Anything

### ISSUE THREAD

**Issue by darrylmorley** [ciderapp/Cider#1586]
### Describe the Bug

Library, podcasts etc sync. But, nothing can be played.

### Steps to Reproduce

Installed form Pop OS store, signed in, does not play.
Removed Pop Os Store version & installed flatpak version from flathub. Nothing will play.

### Environment Information

- OS: Pop OS 22.04
- Desktop Environment: 
- App Version: 1.5.9
- Commit ID:

### How did you download the software?

Flathub

### From log:
```
[2022-12-01 11:59:42.053] [info]  [AppEvents] App started
[2022-12-01 11:59:42.271] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'playbackNotifications.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[2022-12-01 11:59:42.371] [info]  [AppEvents] App ready
[2022-12-01 11:59:42.372] [info]  [Cider] Application is Ready. Creating Window.
[2022-12-01 11:59:42.827] [info]  Setting up handlers for local files
[2022-12-01 11:59:42.834] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=39803
[2022-12-01 11:59:42.871] [info]  WebSocketServer started on port: 26369
[2022-12-01 11:59:42.881] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'up-to-date',
    version: null
  }
}
[2022-12-01 11:59:42.921] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 22807,
      gpuPreference: 0,
      vendorId: 32902
    }
  ]
}
[2022-12-01 11:59:42.923] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-12-01 11:59:42.923] [info]  Cider client port: 39803
[2022-12-01 11:59:42.952] [info]  Cider remote port: 38015
[2022-12-01 11:59:42.955] [info]  remote broadcasted
[2022-12-01 11:59:43.850] [info]  [DiscordRPC][connect] Successfully Connected to Discord. Authed for user: 336092510113890310.
[2022-12-01 11:59:44.047] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-12-01 11:59:44.048] [error] DBusError: org.freedesktop.DBus.Error.ServiceUnknown
    at _methodReturnHandlers.<computed> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at /app/cider/resources/app.asar/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at emitReadable_ (node:internal/streams/readable:578:12)
[2022-12-01 11:59:44.049] [error] (node:12) UnhandledPromiseRejectionWarning: DBusError: org.freedesktop.DBus.Error.ServiceUnknown
    at _methodReturnHandlers.<computed> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at /app/cider/resources/app.asar/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/app/cider/resources/app.asar/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at emitReadable_ (node:internal/streams/readable:578:12)
(Use `cider --trace-warnings ...` to show where the warning was created)
[2022-12-01 11:59:44.049] [error] (node:12) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2022-12-01 12:00:07.905] [info]  [DiscordRPC][connect] Successfully Connected to Discord. Authed for user: 336092510113890310.
```

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by libraakira** [comment]
I'm having a similar issue. When I click the play button beside a song, I get the following error.

`musickit.js:44 Uncaught (in promise) CONTENT_UNSUPPORTED: NO DRM
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:333850
    at MediaItemPlayback.<anonymous> (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:333952)
    at Generator.next (<anonymous>)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:880
    at new Promise (<anonymous>)
    at __awaiter$1 (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:579)
    at MediaItemPlayback.startMediaItemPlayback (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:333456)
    at SerialPlaybackController.<anonymous> (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:260058)
    at Generator.next (<anonymous>)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:880
(anonymous) @ musickit.js:44
(anonymous) @ musickit.js:44
(anonymous) @ musickit.js:15
__awaiter$1 @ musickit.js:15
startMediaItemPlayback @ musickit.js:44
(anonymous) @ musickit.js:44
(anonymous) @ musickit.js:15
__awaiter$1 @ musickit.js:15
_changeToMediaAtIndex @ musickit.js:44
(anonymous) @ musickit.js:44
(anonymous) @ musickit.js:15
__awaiter$1 @ musickit.js:15
_changeToMediaAtIndex @ musickit.js:44
(anonymous) @ musickit.js:44
fulfilled @ musickit.js:15`

**Comment by cryptofyre** [comment]
Linux appears to have an issue with DRM, not much we can do at the moment as its primarily a chromium and or Linux issue.

**Comment by carbonsam** [comment]
Having the same problem, but no error appears in the app or logs. Clicking play just doesn't work, but I can still see everything. On a recent fresh install of Zorin OS, but this was definitely working a few days ago before the reinstall.

**Comment by darrylmorley** [comment]
> Having the same problem, but no error appears in the app or logs. Clicking play just doesn't work, but I can still see everything. On a recent fresh install of Zorin OS, but this was definitely working a few days ago before the reinstall.

Maybe an older version will work?

**Comment by sqrtd** [comment]
Temporary workaround I found:

Install chromium
Copy the contents of .config/chromium/WidevineCdm into .var/app/sh.cider.Cider/config/Cider/WidevineCdm/
Run Cider

**Comment by libraakira** [comment]
Mine was a DRM issue. I got mine working by enabling DRM in Firefox.

**Comment by darrylmorley** [comment]
I checked WideVine & DRM settings in Firefox & Chrome, and everything was already enabled and installed. Ubuntu Extras is already installed. It's now working without anything being changed, which is weird. But, glad it's working!

**Comment by MakufonSkifto** [comment]
I'm having the same issue, been happening for almost a month now.

**Comment by rsramkis** [comment]
> Linux appears to have an issue with DRM, not much we can do at the moment as its primarily a chromium and or Linux issue.

Hi

. In Linux systems I believe the Chromium front end is called Electron.  If there is a DRM issue in Electron which version of Electron and do you have a related bug number?

Thanks

**Comment by rsramkis** [comment]
> Mine was a DRM issue. I got mine working by enabling DRM in Firefox.

What system are you using ... Linux? What distribution and version?

**Comment by rsramkis** [comment]
Interestingly enough I was also getting a "Mediaplay" error this morning from the Cider Flatpak install. I ran the "flatpak update" command from terminal and received a Gnome environment update. I relaunched and all of a sudden Cider would play music.

```
flatpak update
Looking for updates…


        ID                             Branch     Op     Remote      Download
 1. [✓] org.gnome.Platform.Locale      43         u      flathub      17.7 kB / 340.4 MB
 2. [✓] org.gnome.Platform             43         u      flathub     121.7 MB / 325.1 MB

Updates complete.
```

I see serveral comments about changing DRM settings in a Web Browser Chrome and Firefox. As long as we are on Linux, and if Cider uses Electron, then changing web browser settings does not affect Electron.  
 
**Enviroment:**

```
Kernel: 5.15.80-1-lts arch: x86_64 bits: 64
Desktop: GNOME  v: 43.1 Distro: EndeavourOS
```

By the way as you mentioend ... this issue has been going for several days. And mind just started working now. I do understand you are using Pop OS.

**Comment by steveknight** [comment]
Thanks @rsramkis I have been having this exact problem for a few days (KDE on Pop) and `flatpak update` solved it for me.

**Comment by mattmilano** [comment]
This is still occurring for me on two installations of KDE Neon. Hadn't run Cider in a few days, fired it up today, and am receiving MusicKit MediaPlaybackError message. Nothing plays at all.

I've run `flatpak update` and everything is up-to-date, so I'm not sure what the problem is.

**Comment by niklaskorz** [comment]
Same issue with MEDIAPLAYBACKERROR on Windows 11 (winget version) and Arch Linux (aur version).

**Comment by rsramkis** [comment]
I was wondering, after everyone updates Cider via the "flatpak update" command. Have you tried logging out and back in?

I noticed when I was having the MediaPlaybackError that I had to re-authenticate my login to Apple. So this means going into the Cider menu and logging out and then back in. This would also force Apple 2 factor authentication to confirm you are a real person.
