### ISSUE TITLE
[Bug]: Support of custom CA's?

### ISSUE THREAD

**Issue by iaroslav-nakonechnikov** [ciderapp/Cider#1712]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.1

### What operating system are you using?

Ubuntu

### Operating System Version

WSL Ubuntu 22.04

### Where did you download Cider from?

GitHub

### Describe the Bug

Hello, 

due to some internal policies all connections should go thru zscaler. 
and i already installed needed certificates to make it usable, for example, with curl:
```
 curl -vv https://appleid.apple.com/
*   Trying 17.111.105.242:443...
* Connected to appleid.apple.com (17.111.105.242) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: businessCategory=Private Organization; jurisdictionC=US; jurisdictionST=California; serialNumber=C0806592; C=US; ST=California; L=Cupertino; O=Apple Inc.; CN=appleid.apple.com
*  start date: Apr  5 12:10:22 2023 GMT
*  expire date: Oct  2 12:20:22 2023 GMT
*  subjectAltName: host "appleid.apple.com" matched cert's "appleid.apple.com"
*  issuer: C=US; O=Apple Inc.; CN=Apple Public EV Server RSA CA 2 - G1
*  SSL certificate verify ok.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET / HTTP/1.1
> Host: appleid.apple.com
> User-Agent: curl/7.81.0
> Accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Server: Apple
< Date: Mon, 15 May 2023 11:08:50 GMT
< Content-Type: text/html
< Content-Length: 146
< Connection: keep-alive
< Cache-Control: private, no-cache, no-store, max-age=0
<
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>Apple</center>
</body>
</html>
* Connection #0 to host appleid.apple.com left intact
```

but in cider i can't login, it fails with: 
```
[14284:0515/130319.028171:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.NameHasOwner: object_path= /org/freedesktop/DBus: unknown error type:
[14284:0515/130319.715968:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13:03:20.107] [error] [mpris.js] An error was encountered: Error: unknown address type:disabled
[13:03:20.109] [error] Error: unknown address type:disabled
    at createStream (/opt/Cider/resources/app.asar/node_modules/dbus-next/lib/connection.js:64:17)
    at createConnection (/opt/Cider/resources/app.asar/node_modules/dbus-next/lib/connection.js:81:33)
    at createClient (/opt/Cider/resources/app.asar/node_modules/dbus-next/index.js:10:20)
    at Object.sessionBus (/opt/Cider/resources/app.asar/node_modules/dbus-next/index.js:41:10)
    at Player.init (/opt/Cider/resources/app.asar/node_modules/mpris-service/src/index.js:183:20)
    at new Player (/opt/Cider/resources/app.asar/node_modules/mpris-service/src/index.js:175:8)
    at Player (/opt/Cider/resources/app.asar/node_modules/mpris-service/src/index.js:168:12)
    at Function.connect (/opt/Cider/resources/app.asar/src/main/plugins/mpris.ts:50:20)
    at mpris.onRendererReady (/opt/Cider/resources/app.asar/src/main/plugins/mpris.ts:153:11)
    at Plugins.callPlugins (/opt/Cider/resources/app.asar/src/main/base/plugins.ts:107:42)
[14284:0515/130347.740624:ERROR:cert_verify_proc_builtin.cc(677)] CertVerifyProcBuiltin for api.cider.sh failed:
----- Certificate i=2 (emailAddress=support@zscaler.com,CN=Zscaler Intermediate Root CA (zscaler.net),OU=Zscaler Inc.,O=Zscaler Inc.,ST=California,C=US) -----
ERROR: No matching issuer found
```

### Steps to Reproduce

try to run it in system with restricted internet access

**Comment by iaroslav-nakonechnikov** [comment]
executing curl to `connect.cidercollective.dev` from terminal looks working:
```
 curl -vvv "https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000"
*   Trying 104.21.28.105:443...
* Connected to connect.cidercollective.dev (104.21.28.105) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=connect.cidercollective.dev
*  start date: May 13 06:30:36 2023 GMT
*  expire date: May 27 06:30:36 2023 GMT
*  subjectAltName: host "connect.cidercollective.dev" matched cert's "connect.cidercollective.dev"
*  issuer: C=US; ST=California; O=Zscaler Inc.; OU=Zscaler Inc.; CN=Zscaler Intermediate Root CA (zscaler.net) (t)
*  SSL certificate verify ok.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /callback/discord?app=cider&appPort=9000 HTTP/1.1
> Host: connect.cidercollective.dev
> User-Agent: curl/7.81.0
> Accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 15 May 2023 11:13:19 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Cache-Control: public, max-age=0, must-revalidate
< referrer-policy: strict-origin-when-cross-origin
< x-content-type-options: nosniff
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=6O9AJLd64wy8UkRluMftlG3h1gLMNiXieBQRUPnBEMrPYbtJH5Pk5Ij%2FLhTh9h8PIkbXTe51Ldl9zfAxDE1N0Zs5A16tDEH6BzGdwL0r%2BkuNUytu%2FvnOgrdqXSwBZU0oo%2BblQry0OW9mw9%2B87kA%3D"}],"group":"cf-nel","max_age":604800}
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< Vary: Accept-Encoding
< CF-Cache-Status: DYNAMIC
< Server: cloudflare
< CF-RAY: 7c7af3737dc59237-FRA
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
<
* Connection #0 to host connect.cidercollective.dev left intact
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/logo400.jpeg"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="apple-touch-icon" href="/logo192.png"/><link rel="manifest" href="/manifest.json"/><script defer="defer" src="/static/js/main.8e3c60bd.js"></script><link href="/static/css/main.7ec66d7a.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><!-- Cloudflare Pages Analytics --><script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "38ba04e149c24e03bd1c518ad8cfb2df"}'></script><!-- Cloudflare Pages Analytics --></body></html>
```
