### ISSUE TITLE
[Bug]: Cider failed to build (arch repo)

### ISSUE THREAD

**Issue by ahloiscreamo** [ciderapp/Cider#535]
### Describe the Bug

Install cider via arch repo, went through build process and failed to build.

```
❯ yay -Syu --aur
:: Searching AUR for updates...
 -> otf-sfmono-patched: local (20200824-1) is newer than AUR (20191114-1)
 -> sanskrit-fonts: local (1.1-1) is newer than AUR (r33.15a2dd4-1)
 -> ttf-tw: local (1:20220110-1) is newer than AUR (1:20210727-1)
 -> Missing AUR Packages:  mpd-art-box
:: 1 Packages to upgrade.
1  aur/cider  1.1.0.1837.06289d2-1 -> 1.1.0.1841.2a9622fa-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo Make:1]  yarn-1.22.17-1
[Aur:1]  cider-1.1.0.1841.2a9622fa-1

==> Remove make dependencies after install? [y/N] y
  1 cider                            (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/ahloi/.cache/yay/cider
:: (1/1) Downloaded PKGBUILD: cider
  1 cider                            (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: (1/1) Parsing SRCINFO: cider
:: Synchronizing package databases...
 system is up to date
 world is up to date
 galaxy is up to date
 extra is up to date
 community is up to date
 multilib is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) yarn-1.22.17-1

Total Installed Size:  5.08 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                     [###########] 100%
(1/1) checking package integrity                   [###########] 100%
(1/1) loading package files                        [###########] 100%
(1/1) checking for file conflicts                  [###########] 100%
(1/1) checking available disk space                [###########] 100%
:: Processing package changes...
(1/1) installing yarn                              [###########] 100%
==> Making package: cider 1.1.0.1841.2a9622fa-1 (Selasa 01 Mac 2022 09:50:09 )
==> Retrieving sources...
  -> Cloning Cider git repo...
Cloning into bare repository '/home/ahloi/.cache/yay/cider/Cider'...
remote: Enumerating objects: 18307, done.
remote: Counting objects: 100% (7552/7552), done.
remote: Compressing objects: 100% (1845/1845), done.
remote: Total 18307 (delta 6263), reused 6704 (delta 5646), pack-reused 10755
Receiving objects: 100% (18307/18307), 17.12 MiB | 1.17 MiB/s, done.
Resolving deltas: 100% (12352/12352), done.
  -> Found Cider.desktop
==> Validating source files with sha256sums...
    Cider ... Skipped
    Cider.desktop ... Passed
 -> yarn not satisfied, flushing install queue
==> Making package: cider 1.1.0.1841.2a9622fa-1 (Selasa 01 Mac 2022 09:50:27 )
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating Cider git repo...
Fetching origin
  -> Found Cider.desktop
==> Validating source files with sha256sums...
    Cider ... Skipped
    Cider.desktop ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of Cider git repo...
Cloning into 'Cider'...
done.
==> Starting pkgver()...
==> Sources are ready.
==> Making package: cider 1.1.0.1841.2a9622fa-1 (Selasa 01 Mac 2022 09:50:31 )
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
Building Cider on v1.1.0.1841.2a9622fa : [Install Build Dependencies] | Build | Done
yarn install v1.22.17
info No lockfile found.
[1/4] Resolving packages...
warning electron-builder > dmg-builder > dmg-license@1.0.11: Disk image license agreements are deprecated by Apple and will probably be removed in a future macOS release. Discussion at: https://github.com/argv-minus-one/dmg-license/issues/11
warning electron-webpack > webpack-dev-server > chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
warning electron-webpack > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning electron-webpack > webpack-dev-server > webpack-log > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning electron-webpack > webpack-dev-server > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning electron-webpack > webpack-cli > findup-sync > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning electron-webpack > webpack-cli > findup-sync > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning electron-webpack > webpack-cli > findup-sync > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning electron-webpack > webpack-cli > findup-sync > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > electron-webpack@2.8.2" has incorrect peer dependency "webpack@^4.42.1".
warning "electron-webpack > mini-css-extract-plugin@0.9.0" has incorrect peer dependency "webpack@^4.4.0".
warning "electron-webpack > webpack-cli@3.3.12" has incorrect peer dependency "webpack@4.x.x".
[4/4] Building fresh packages...
[1/4] ⠐ register-scheme
[2/4] ⠐ abstract-socket
[3/4] ⠐ electron
error /home/ahloi/.cache/yay/cider/src/Cider/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/ahloi/.cache/yay/cider/src/Cider/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v18.0.0-alpha.5+wvcus/electron-v18.0.0-alpha.5+wvcus-linux-x64.zip
    at EventEmitter.<anonymous> (/home/ahloi/.cache/yay/cider/src/Cider/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:390:28)
    at module.exports (/home/ahloi/.cache/yay/cider/src/Cider/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/home/ahloi/.cache/yay/cider/src/Cider/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/home/ahloi/.cache/yay/cider/src/Cider/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)


==> ERROR: A failure occurred in build().
    Aborting...
checking dependencies...

Packages (1) yarn-1.22.17-1

Total Removed Size:  5.08 MiB

:: Do you want to remove these packages? [Y/n] 
:: Processing package changes...
(1/1) removing yarn                                [###########] 100%
 -> error making: cider
~ 2m 38s
❯ 
```

### Steps to Reproduce

upgrade arch repo, upgrade cider=failed.

### Environment Information

- OS:Artix 
- App Version:1.1.0
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Make sure you have no existing instance running

**Comment by ahloiscreamo** [comment]
@coredev-uk 
There is no other instance running.
So i installed cider successfully on arch repo, and it yielded the similar problem 
Thanks for the feedback, i will figure out on how to work on this dbus error

```
~
❯ cider 
[20439:0302/013050.320145:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[20439:0302/013050.320309:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[20498:0302/013050.496167:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
~ 38s
❯ 
 
```

**Comment by coredev-uk** [comment]
I believe that error is either related to the mpris plugin or the web remote

**Comment by coredev-uk** [comment]
I believe the AUR package is back in operation now with that weird git bug, try installing that now and all dependencies that the app requires will be installed. If you have further issues open a new issue.
