### ISSUE TITLE
[Bug]: Songs are not playing when clicked

### ISSUE THREAD

**Issue by Xenfo** [ciderapp/Cider#611]
### Describe the Bug

I click on a song in a playlist and nothing happens. Some songs do play but others don't.

### Steps to Reproduce

1. A song in a playlist
2. It might not play

### Environment Information

- OS: Arch Linux
- App Version: 1.3.0
- Commit ID: 3c45ec5c

Entire string: `cider-git 1.3.0.2803.3c45ec5c-1`

### Anything else?

https://user-images.githubusercontent.com/46873232/159683355-23d4231c-9537-4ccf-81bb-aff8f22123e6.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RussianSlavv** [comment]
Same here, Windows 10 and Latest update from the microsoft store installed

**Comment by cryptofyre** [comment]
Please attach logs from the dev tools console using CTRL+SHIFT+I so we can investigate this further.

**Comment by Xenfo** [comment]
```
Loaded Preload
VM224:159 Setting ipcRenderer
less.js:10 Rendered http://localhost:9000/themes/default.less successfully.
less.js:10 CSS for http://localhost:9000/themes/default.less generated in 29ms
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/less.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/vuedraggable.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
resonance-audio.min.js:166 [Omnitone] Version 1.0.6 (running Chrome 96.0.4664.110 on Linux) (@327.70ms)
DevTools failed to load source map: Could not load content for http://localhost:9000/CiderHls.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/bootstrap-vue.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/bootstrap.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/showdown.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/stackblur.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.js?v=1:264 WebGPU disabled / WebGPU initialization failed
index.js?v=1:120 MusicKit loaded
DevTools failed to load source map: Could not load content for https://js-cdn.music.apple.com/hls.js/2.141.0/hls.js/hls.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
less.js:10 Rendered http://localhost:9000/style.less successfully.
less.js:10 CSS for http://localhost:9000/style.less generated in 1869ms
less.js:10 Less has finished. CSS generated in 1898ms
DevTools failed to load source map: Could not load content for http://localhost:9000/sw.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
workbox-962786f2.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"http://localhost:9000/musickit.js","status":404}]
    at O.C (http://localhost:9000/workbox-962786f2.js:1:10428)
    at async O.U (http://localhost:9000/workbox-962786f2.js:1:10026)
    at async O.v (http://localhost:9000/workbox-962786f2.js:1:7520)
s @ workbox-962786f2.js:1
C @ workbox-962786f2.js:1
setTimeout (async)
(anonymous) @ workbox-962786f2.js:1
cachePut @ workbox-962786f2.js:1
C @ workbox-962786f2.js:1
await in C (async)
U @ workbox-962786f2.js:1
await in U (async)
v @ workbox-962786f2.js:1
await in v (async)
handleAll @ workbox-962786f2.js:1
(anonymous) @ workbox-962786f2.js:1
await in (anonymous) (async)
v @ workbox-962786f2.js:1
install @ workbox-962786f2.js:1
DevTools failed to load source map: Could not load content for http://localhost:9000/workbox-962786f2.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/less/bootstrap-vue.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
musickit.js:44 GET https://amp-api.music.apple.com/v1/storefronts/undefined 404
(anonymous) @ musickit.js:44
(anonymous) @ musickit.js:29
__awaiter @ musickit.js:29
(anonymous) @ musickit.js:44
(anonymous) @ musickit.js:44
constructUrlMiddleware @ musickit.js:44
(anonymous) @ musickit.js:44
processMiddleware @ musickit.js:44
request @ musickit.js:44
MKJSLang @ vueapp.js:3953
setLz @ vueapp.js:299
init @ vueapp.js:576
waitForApp @ index.js?v=1:136
setTimeout (async)
waitForApp @ index.js?v=1:142
setTimeout (async)
waitForApp @ index.js?v=1:142
(anonymous) @ index.js?v=1:145
Promise.then (async)
initMusicKit @ index.js?v=1:133
load (async)
(anonymous) @ index.js?v=1:152
(anonymous) @ musickit.js:44
setTimeout (async)
dispatchDocumentEvent @ musickit.js:44
(anonymous) @ musickit.js:44
(anonymous) @ musickit.js:1
(anonymous) @ musickit.js:1
vueapp.js:3974 locale err NOT_FOUND: 404
    at Function.responseError (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:3627)
    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:250888
    at Generator.next (<anonymous>)
    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:29:977)
vueapp.js:3958 (2) ['en-ca', 'fr-ca']
vueapp.js:3971 en-ca
vueapp.js:714 SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Cn.init (vueapp.js:672)
vueapp.js:1028 using cached playlists
vueapp.js:1036 using cached track mapping
vueapp.js:1047 scanning p.playlistsroot
(index):2802 {id: '7-2Tqlz47h9yro', type: 'personal-recommendation', href: '/v1/me/recommendations/7-2Tqlz47h9yro?l=en-CA&name=listen-now', attributes: {…}, relationships: {…}, …}
vueapp.js:2413 {…}
cidercache.js:15 Caching library-playlists-tracks
cidercache.js:15 Caching library-playlists
(index):8295 {…} 'playlist:p.XMrm7EYiOAogq6E' 0 'song' 'i.O1RG3W5S8YNaz30' true false false
vueapp.js:2937 playlists p.XMrm7EYiOAogq6E
(index):8295 {…} 'playlist:p.XMrm7EYiOAogq6E' 1 'song' 'i.AWPNG5dhN0xQpGl' true false false
vueapp.js:2937 playlists p.XMrm7EYiOAogq6E
(index):8295 {…} 'playlist:p.XMrm7EYiOAogq6E' 2 'song' 'i.qQdGNYliNWQDzl8' true false false
vueapp.js:2937 playlists p.XMrm7EYiOAogq6E
(index):8295 {…} 'playlist:p.XMrm7EYiOAogq6E' 3 'song' 'i.gelJra9SR0qG8Xd' true false false
vueapp.js:2937 playlists p.XMrm7EYiOAogq6E
(index):8295 {…} 'playlist:p.XMrm7EYiOAogq6E' 4 'song' 'i.PkdZ7GZTPaKm97E' true false false
vueapp.js:2937 playlists p.XMrm7EYiOAogq6E
VM224:28 nowPlayingItemDidChange
```

**Comment by Xenfo** [comment]
Not stale

**Comment by Xenfo** [comment]
Not stale

**Comment by KillerParticles** [comment]
Have you tried turning on Content Restrictions on your account and setting them to explicit? You say some play and some don't, I'm guessing only the explicit ones like the one in your video do not play. Go to [your web account settings](https://tv.apple.com/settings), turn **on** content restrictions and set them to explicit. (has to be the ones at this link, not the ones on your iPhone or iPad.

**Comment by Xenfo** [comment]
It seems to be fixed on Windows, not sure about other OSs. The link doesn't work in Canada for some reason, I think Apple TV might be limited via browser in other countries.
