### ISSUE TITLE
[Bug]: DiscordRPC configuration migrations

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Cider#973]
### Describe the Bug

When upgrading from Cider 1.4.2 to newer versions, DiscordRPC configurations do not get properly migrated, leaving blank and un-saveable fields in Settings.

With my testing, this **only happens on CircleCI builds**. Self-compiled builds are not affected by this issue.

### Steps to Reproduce

Blank fields:  
1. Install Cider 1.4.2
2. Run Cider once to generate configuration files
3. Upgrade to newer versions (try the current CI builds)
4. Run Cider and go to Settings → Connectivity
5. See error

Un-saveable configurations:
1. Change any settings fields under `Discord Rich Presence` (toggle), `Client Name` (dropdown), `Clear Discord Rich Presence on Pause` (toggle), `Hide buttons on Discord Rich Presence` (toggle), `Details Format` (text field), `State Format` (text field)
2. Exit Settings and re-enter Settings → Connectivity
3. See error

### Environment Information

- **OS:** Windows 10 Pro 21H2 (19044.1645)
- **App Version** and/or **Commit ID:** 1.4.2-alpha.1750, 1.4.5-alpha.2031

### Anything else?

![Cider settings, with a rectangle drawn around the error.](https://user-images.githubusercontent.com/32032824/166155232-e25dd526-69b6-4cdf-88c9-104aabd82aa6.png)

Console errors when changing the blank configs:
```
vue.js:6 TypeError: Cannot use 'in' operator to search for 'enabled' in 1
    at a.ke [as $set] (vue.js:6:7716)
    at change (eval at Qa (vue.js:6:92206), <anonymous>:7:40840)
    at Be (vue.js:6:11394)
    at HTMLInputElement.n (vue.js:6:13178)
    at HTMLInputElement.Qr.o._wrapper (vue.js:6:48900)
Ve @ vue.js:6
vue.js:6 TypeError: Cannot use 'in' operator to search for 'client' in 1
    at a.ke [as $set] (vue.js:6:7716)
    at change (eval at Qa (vue.js:6:92206), <anonymous>:7:41763)
    at Be (vue.js:6:11394)
    at HTMLSelectElement.n (vue.js:6:13178)
    at HTMLSelectElement.Qr.o._wrapper (vue.js:6:48900)
Ve @ vue.js:6
vue.js:6 TypeError: Cannot use 'in' operator to search for 'clear_on_pause' in 1
    at a.ke [as $set] (vue.js:6:7716)
    at change (eval at Qa (vue.js:6:92206), <anonymous>:7:43351)
    at Be (vue.js:6:11394)
    at HTMLInputElement.n (vue.js:6:13178)
    at HTMLInputElement.Qr.o._wrapper (vue.js:6:48900)
Ve @ vue.js:6
vue.js:6 TypeError: Cannot use 'in' operator to search for 'hide_buttons' in 1
    at a.ke [as $set] (vue.js:6:7716)
    at change (eval at Qa (vue.js:6:92206), <anonymous>:7:44664)
    at Be (vue.js:6:11394)
    at HTMLInputElement.n (vue.js:6:13178)
    at HTMLInputElement.Qr.o._wrapper (vue.js:6:48900)
Ve @ vue.js:6
vue.js:6 TypeError: Cannot use 'in' operator to search for 'details_format' in 1
    at a.ke [as $set] (vue.js:6:7716)
    at input (eval at Qa (vue.js:6:92206), <anonymous>:7:45659)
    at Be (vue.js:6:11394)
    at HTMLInputElement.n (vue.js:6:13178)
    at HTMLInputElement.Qr.o._wrapper (vue.js:6:48900)
Ve @ vue.js:6
vue.js:6 TypeError: Cannot use 'in' operator to search for 'state_format' in 1
    at a.ke [as $set] (vue.js:6:7716)
    at input (eval at Qa (vue.js:6:92206), <anonymous>:7:46683)
    at Be (vue.js:6:11394)
    at HTMLInputElement.n (vue.js:6:13178)
    at HTMLInputElement.Qr.o._wrapper (vue.js:6:48900)
Ve @ vue.js:6
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SoNothingMC** [comment]
Even more info:

**Cider configurations on 1.4.2-alpha.1750:** https://pastebin.com/PCaHdJVr
(I removed the `ENV` values as they contain private information, and changed the client name from `Cider` to `Apple Music`, but nothing else has changed.)

**Cider configurations after updating to 1.4.5-alpha.2031:** https://pastebin.com/y6pL98TT
(`ENV` values are removed - reason above.)

**Comment by coredev-uk** [comment]
There is a migration that I put in to prevent this, not sure why users on the latest builds are still experiencing this issue.
